name: Get containers

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
    get-containers:
      runs-on: ubuntu-latest
      steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Get containers
        uses: Netcracker/qubership-hub-test/actions/container-get@main
        env:
          PACKAGE_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
